### ISSUE TITLE
adding SBOM scanning capability into the worklofw

### ISSUE THREAD

**Issue by developer-guy** [marcofranssen/slsa-workflow-examples#2]
Hello @marcofranssen, thanks for this great resource that you covered all the details about making software supply chains even more secure with the help of a bunch of open-source tools. I thought that maybe we can add SBOM scanning capability into the puzzle to scan all the packages available on SBOM results are in good shape, I'm proposing to use [scan-action](https://github.com/anchore/scan-action) from Anchore.

Please tell me what are you thinking about this?

Thanks

**Comment by marcofranssen** [comment]
Great idea, if you do have time, feel free to contribute.
